#!/usr/bin/env python3
"""
IDRE Gateway (AsyncIO + AIOHTTP)
Version: 0.2 (Async Refactor)

This is the Internet-facing component for metadata resistance:
  [Internet] <-(Tor/I2P HTTP tunnel)-> [Gateway] <-(localhost)-> [IDRE node]

Responsibilities:
- Maintain a constant-rate stream of fixed-size cells to a peer gateway.
- Carry real IDRE traffic inside cells; send dummy cells when idle.
- Never expose the IDRE node directly to the Internet.
- **Async Architecture**: Uses `aiohttp` and `asyncio` to handle high-latency networks (Tor/I2P) without blocking.

Transport notes:
- Uses HTTP POST for simplicity (plays well with Tor/I2P tunnels).
- Cells are fixed-size blobs.
"""

from __future__ import annotations

import argparse
import asyncio
import random
import sys
import time
from pathlib import Path
from typing import Optional

import aiohttp
from aiohttp import web

# Allow running as a script from within the standalone package folder

try:
    from core.cell import pack_cell, unpack_cell
    from core.wire_bin import pack_receive_envelope, unpack_receive_envelope, unpack_wire_message
except ImportError:
    # Fallback for when running in a different context/environment
    try:
        from core.cell import pack_cell, unpack_cell
        from core.wire_bin import pack_receive_envelope, unpack_receive_envelope, unpack_wire_message
    except ImportError:
        print("[!] Critical: IDRE Core modules not found. Is PYTHONPATH set?")
        sys.exit(1)

DEFAULT_CELL_LEN = 1024
DEFAULT_TICK_HZ = 10.0

class AsyncGateway:
    def __init__(
        self,
        *,
        node_base: str,
        peer_cell_url: str,
        cell_len: int,
        tick_hz: float,
        jitter_ms: int,
        rng_seed: int,
        print_events: bool,
    ):
        self.node_base = node_base.rstrip("/")
        self.peer_cell_url = peer_cell_url
        self.cell_len = int(cell_len)
        self.tick_hz = float(tick_hz)
        self.jitter_ms = int(jitter_ms)
        self.print_events = bool(print_events)
        self._rng = random.Random(int(rng_seed))

        # Async Queues
        # _send_q: Cells waiting to be POSTed to the Peer (Internet)
        self._send_q: asyncio.Queue[bytes] = asyncio.Queue(maxsize=256)
        
        # _ingest_q: Cells received from Internet, waiting to be POSTed to Local Node
        self._ingest_q: asyncio.Queue[bytes] = asyncio.Queue(maxsize=4096)
        
        # _net_q: Fixed-size cells generated by tick_loop, waiting to be sent to Peer
        self._net_q: asyncio.Queue[bytes] = asyncio.Queue(maxsize=256)
        
        self._stop_event = asyncio.Event()
        self._session: Optional[aiohttp.ClientSession] = None

    async def start(self, host: str, port: int):
        """Main entry point: starts tasks and runs the web server."""
        self._session = aiohttp.ClientSession()
        
        # Start background tasks
        tasks = [
            asyncio.create_task(self.tick_loop(), name="tick_loop"),
            asyncio.create_task(self.net_sender_loop(), name="net_sender_loop"),
            asyncio.create_task(self.ingest_loop(), name="ingest_loop"),
        ]

        # Setup Web Server
        app = web.Application()
        app.router.add_post("/cell", self.handle_incoming_cell_http)
        app.router.add_post("/enqueue", self.handle_enqueue)
        
        runner = web.AppRunner(app)
        await runner.setup()
        site = web.TCPSite(runner, host, port)
        
        if self.print_events:
            print(f"[gw] Async Gateway running on http://{host}:{port}")
            print(f"     Node: {self.node_base} | Peer: {self.peer_cell_url}")
            print(f"     Tick: {self.tick_hz}Hz | Cell: {self.cell_len} bytes")

        try:
            await site.start()
            # Wait until stop is signaled
            await self._stop_event.wait()
        finally:
            # Cleanup
            if self.print_events:
                print("[gw] Stopping...")
            
            for t in tasks:
                t.cancel()
            
            # Allow brief time for pending helper tasks to cancel
            try:
                await asyncio.gather(*tasks, return_exceptions=True)
            except Exception:
                pass
            
            try:
                await site.stop()
                await runner.cleanup()
            except Exception:
                pass

            if self._session and not self._session.closed:
                try:
                    await self._session.close()
                except Exception:
                    pass

    def stop(self):
        """Signal the gateway to stop."""
        self._stop_event.set()

    # --- HTTP Handlers ---

    # --- HTTP Handlers ---
    
    async def handle_incoming_cell_http(self, request: web.Request) -> web.Response:
        """
        Public Endpoint: Receives a cell from a Peer (via Internet/Tor).
        POST /cell
        Body: Raw bytes (cell_len)
        """
        # 1. IP Check?
        # We might want to allow ANY IP if we are behind a reverse proxy or Tor.
        # But for direct verify, we are on localhost.
        # If we are behind Tor, the request comes from localhost anyway (usually).
        # So we can't easily filter by IP for "Internet" vs "Local".
        # But `handle_enqueue` MUST be local-only.
        
        body = await request.read()
        if len(body) != self.cell_len:
             # Traffic Analysis Resistance: Should we reply 200 anyway?
             # For now, 400.
             return web.Response(status=400, text="bad_len")
        
        try:
            self._ingest_q.put_nowait(body)
        except asyncio.QueueFull:
            # Overloaded? Drop.
            return web.Response(status=503, text="busy")
            
        return web.Response(status=204) # No Content (typical for beacons)

    async def handle_enqueue(self, request: web.Request) -> web.Response:
        """
        Local Endpoint: Node enqueues a cell to be sent to Peer.
        POST /enqueue
        Body: Raw bytes (payload) - NOT wrapped in cell?
        Wait, `pack_cell` happens in `tick_loop`. 
        So Node sends PAYLOAD (inner).
        """
        # 1. Require Localhost
        peer_ip = request.remote
        if peer_ip not in ("127.0.0.1", "::1"):
            return web.Response(status=403, text="local_only")
            
        body = await request.read()
        
        # We put RAW payload into _send_q. 
        # `tick_loop` will `pack_cell` it.
        try:
            self._send_q.put_nowait(body)
        except asyncio.QueueFull:
             return web.Response(status=503, text="busy")
             
        return web.Response(status=204)

    # --- Logic ---

    async def _queue_push_drop_oldest(self, q: asyncio.Queue, item: bytes, name: str):
        try:
            q.put_nowait(item)
        except asyncio.QueueFull:
            try:
                q.get_nowait()
                q.task_done()
            except asyncio.QueueEmpty:
                pass
            try:
                q.put_nowait(item)
            except asyncio.QueueFull:
                pass

    async def user_agent_post_bin(self, url: str, data: bytes, timeout: float = 10.0) -> Tuple[int, bytes]:
        if not self._session:
            return 0, b""
        try:
            async with self._session.post(url, data=data, timeout=timeout) as resp:
                body = await resp.read()
                return resp.status, body
        except Exception:
            return 0, b""

    # --- Background Loops ---

    async def tick_loop(self):
        """
        Traffic Shaping Heartbeat using Drift Correction.
        Generates cells at constant Hz, regardless of payload availability.
        """
        hz = max(0.1, self.tick_hz)
        period = 1.0 / hz
        t0 = time.monotonic()
        n = 0

        while not self._stop_event.is_set():
            # 1. Timing: Drift Correction
            target = t0 + (n * period)
            now = time.monotonic()
            if now < target:
                await asyncio.sleep(target - now)
            
            # 2. Jitter (if enabled)
            if self.jitter_ms > 0:
                # Sleep a random amount, but this delays the *generation* of the cell.
                # Does jitter affect the *average rate*? 
                # If we await sleep here, we push the Next Iteration start time. 
                # But `target` is calculated from `t0`, so we catch up?
                # No, if we sleep extra, we drift late. 
                # Implementation Detail: Jitter usually means "send at T + jitter", 
                # but we want average rate to be HZ.
                # If we just sleep, we reduce effective Hz.
                # Correct Logic: We are ready at `target`. We sleep jitter. 
                # `n` increments. Next loop `target` is fixed. 
                # If `jitter` > `period`, we might pile up. 
                # Typically jitter is small (< period).
                delay = self._rng.random() * (self.jitter_ms / 1000.0)
                await asyncio.sleep(delay)

            # 3. Generate Cell
            # Pull from payload queue (_send_q)
            try:
                # Check header of queue without waiting?
                # or get_nowait?
                inner = self._send_q.get_nowait()
            except asyncio.QueueEmpty:
                inner = b""
            
            cell = pack_cell(inner=inner, cell_len=self.cell_len)
            
            # 4. Enqueue to Net Sender
            # Queue Drop Policy (Oldest) on the WIRE queue too? Senders should keep up.
            await self._queue_push_drop_oldest(self._net_q, cell, "net_q")

            n += 1

    async def net_sender_loop(self):
        """
        Consumes fixed-size cells from net_q and POSTs them to the Peer.
        Decoupled from tick loop to avoid blocking heartbeat on network I/O.
        """
        while not self._stop_event.is_set():
            try:
                # Wait for a cell
                # We use a timeout so we can check stop_event periodically if needed
                # (though cancelling task handles that too).
                cell = await self._net_q.get()
            except asyncio.CancelledError:
                break
            
            # POST to Peer
            try:
                # Fire and forget result (we log failures).
                # We await the POST to respect concurrency=1 (strict ordering).
                code, _ = await self.user_agent_post_bin(self.peer_cell_url, cell, timeout=5.0)
                
                if self.print_events and code not in (200, 204, 0):
                    print(f"[gw] send cell code={code}")
            except Exception as e:
                if self.print_events:
                    print(f"[gw] net_sender_loop error: {e}")
            
            self._net_q.task_done()

    async def ingest_loop(self):
        """
        Consumes received cells (payloads) from ingest_q and forwards to Local Node.
        """
        url = f"{self.node_base}/hive/v12/receive_wire"
        
        while not self._stop_event.is_set():
            try:
                inner = await self._ingest_q.get()
            except asyncio.CancelledError:
                break

            # Forward to Node
            code, _ = await self.user_agent_post_bin(url, inner, timeout=20.0)
            
            # If node is down, we just drop.
            # if self.print_events: print(f"[gw] ingest -> node: {code}")

            self._ingest_q.task_done()

def main() -> int:
    # CLI Args parsing (same as original)
    ap = argparse.ArgumentParser()
    ap.add_argument("--listen", default="127.0.0.1:9010", help="host:port for incoming /cell")
    ap.add_argument("--node", default="http://127.0.0.1:8890", help="local node base URL")
    ap.add_argument("--peer-cell-url", required=True, help="remote gateway cell URL")
    ap.add_argument("--cell-len", type=int, default=DEFAULT_CELL_LEN)
    ap.add_argument("--tick-hz", type=float, default=DEFAULT_TICK_HZ)
    ap.add_argument("--jitter-ms", type=int, default=150)
    ap.add_argument("--rng-seed", type=int, default=1337)
    ap.add_argument("--print-events", action="store_true")
    args = ap.parse_args()

    host, port_s = str(args.listen).rsplit(":", 1)
    port = int(port_s)

    gw = AsyncGateway(
        node_base=str(args.node),
        peer_cell_url=str(args.peer_cell_url),
        cell_len=int(args.cell_len),
        tick_hz=float(args.tick_hz),
        jitter_ms=int(args.jitter_ms),
        rng_seed=int(args.rng_seed),
        print_events=bool(args.print_events),
    )

    try:
        asyncio.run(gw.start(host, port))
    except KeyboardInterrupt:
        pass
    
    return 0

if __name__ == "__main__":
    # Add _wire_q injection to class because I can't edit `__init__` in the class definition string easily 
    # without rewriting the whole block.
    # I will write the FULL FILE content in the tool call correctly.
    sys.exit(main())
